// Database Durable Object -- single instance holding all persistent data in SQLite.
// Uses DO RPC for direct method calls from the Worker.
// Users have UUID primary keys; handles are display names with a unique index.
//
// Business logic is split into submodules:
//   schema.ts        -- DDL, migrations, startup cleanup
//   users.ts         -- user CRUD, handle uniqueness, GitHub OAuth, agent profiles
//   web-sessions.ts  -- cookie-based web dashboard sessions
//   rate-limits.ts   -- sliding 24h rate limit buckets (incl. atomic check+consume)
//   user-metrics.ts  -- lifetime metric accumulation per handle
//   user-teams.ts    -- cross-project team membership join table
//   rank.ts          -- global developer percentile rank query
//   stats.ts         -- community-intelligence aggregates
//   suggestions.ts   -- tool suggestion queue
//   evaluations.ts   -- tool directory CRUD
//   pricing.ts       -- model pricing snapshot + atomic refresh
//
// This file owns the class shell, schema initialization, and the thin RPC
// wrappers that tie it all together.

import { DurableObject } from 'cloudflare:workers';
import type {
  Env,
  DOResult,
  DOError,
  User,
  NewUser,
  RateLimitCheck,
  WebSession,
  UserTeam,
  AgentProfile,
} from '../../types.js';

import { ensureSchema as ensureSchemaFn, cleanup as schemaCleanup } from './schema.js';
import {
  createUser as createUserFn,
  getUser as getUserFn,
  getUserByHandle as getUserByHandleFn,
  updateHandle as updateHandleFn,
  updateColor as updateColorFn,
  setStatus as setStatusFn,
  updateBudgets as updateBudgetsFn,
  getUserByGithubId as getUserByGithubIdFn,
  createUserFromGithub as createUserFromGithubFn,
  linkGithub as linkGithubFn,
  unlinkGithub as unlinkGithubFn,
  updateAgentProfile as updateAgentProfileFn,
} from './users.js';
import {
  createWebSession as createWebSessionFn,
  getWebSession as getWebSessionFn,
  revokeWebSession as revokeWebSessionFn,
  getUserWebSessions as getUserWebSessionsFn,
} from './web-sessions.js';
import {
  checkRateLimit as checkRateLimitFn,
  consumeRateLimit as consumeRateLimitFn,
  checkAndConsume as checkAndConsumeFn,
} from './rate-limits.js';
import { updateUserMetrics as updateUserMetricsFn } from './user-metrics.js';
import {
  addUserTeam as addUserTeamFn,
  getUserTeams as getUserTeamsFn,
  removeUserTeam as removeUserTeamFn,
} from './user-teams.js';
import { getUserGlobalRank as getUserGlobalRankFn } from './rank.js';
import { getStats as getStatsFn, type CommunityStats } from './stats.js';
import {
  saveSuggestion as saveSuggestionFn,
  listSuggestions as listSuggestionsFn,
  reviewSuggestion as reviewSuggestionFn,
  type SuggestionInput,
} from './suggestions.js';
import {
  saveEvaluation as saveEvalFn,
  getEvaluation as getEvalFn,
  listEvaluations as listEvalsFn,
  searchEvaluations as searchEvalsFn,
  deleteEvaluation as deleteEvalFn,
  getDirectoryStats as getDirectoryStatsFn,
  type EvaluationInput,
  type ListFilters,
} from './evaluations.js';
import {
  getModelPricesSnapshot as getModelPricesSnapshotFn,
  getPricingMetadata as getPricingMetadataFn,
  getModelCanonicalNames as getModelCanonicalNamesFn,
  upsertModelPricesTxn as upsertModelPricesTxnFn,
  recordRefreshFailure as recordRefreshFailureFn,
  seedFromBundled as seedFromBundledFn,
  type ModelPriceInput,
  type PricingMetadataInput,
  type ModelPricesSnapshot,
  type PricingMetadata,
  type BundledPricingSeed,
} from './pricing.js';
// Bundled pricing snapshot — used on fresh deploys where the 6h refresh cron
// hasn't fired yet. Regenerated by `npm run build:pricing-seed`. Never
// hand-edited. See packages/worker/scripts/fetch-pricing-seed.ts.
// `resolveJsonModule: true` in tsconfig enables this import; no runtime
// assertion needed with the "bundler" moduleResolution + "ES2022" module.
import pricingSeed from '../../lib/pricing-seed.json';

export class DatabaseDO extends DurableObject<Env> {
  sql: SqlStorage;
  #schemaReady = false;

  #transact: <T>(fn: () => T) => T;

  constructor(ctx: DurableObjectState, env: Env) {
    super(ctx, env);
    this.sql = ctx.storage.sql;
    this.#transact = <T>(fn: () => T): T => ctx.storage.transactionSync(fn);
  }

  #ensureSchema(): void {
    if (this.#schemaReady) return;

    ensureSchemaFn(this.sql, this.#transact);

    // Prune stale rate limit rows and expired sessions (runs every startup,
    // not a migration -- these are recurring cleanup, not schema changes)
    schemaCleanup(this.sql);

    // One-time seed from the bundled pricing snapshot if model_prices is
    // empty (fresh deploy, cron hasn't fired yet). No-op on every other
    // cold start. The seed is replaced by the first successful cron refresh.
    seedFromBundledFn(this.sql, this.#transact, pricingSeed as BundledPricingSeed);

    this.#schemaReady = true;
  }

  // -- Users --

  async createUser(): Promise<DOResult<NewUser & { ok: true }>> {
    this.#ensureSchema();
    return createUserFn(this.sql);
  }

  async getUser(id: string): Promise<DOResult<{ ok: true; user: User }>> {
    this.#ensureSchema();
    return getUserFn(this.sql, id);
  }

  async getUserByHandle(handle: string): Promise<DOResult<{ ok: true; user: User }>> {
    this.#ensureSchema();
    return getUserByHandleFn(this.sql, handle);
  }

  async updateHandle(
    userId: string,
    newHandle: string,
  ): Promise<DOResult<{ ok: true; handle: string }>> {
    this.#ensureSchema();
    return updateHandleFn(this.sql, userId, newHandle);
  }

  async updateColor(userId: string, color: string): Promise<DOResult<{ ok: true; color: string }>> {
    this.#ensureSchema();
    return updateColorFn(this.sql, userId, color);
  }

  async setStatus(userId: string, status: string | null): Promise<{ ok: true }> {
    this.#ensureSchema();
    return setStatusFn(this.sql, userId, status);
  }

  async updateBudgets(
    userId: string,
    input: unknown,
  ): Promise<DOResult<{ ok: true; budgets: Record<string, unknown> | null }>> {
    this.#ensureSchema();
    return updateBudgetsFn(this.sql, userId, input);
  }

  // -- GitHub OAuth --

  async getUserByGithubId(githubId: string | number): Promise<DOResult<{ ok: true; user: User }>> {
    this.#ensureSchema();
    return getUserByGithubIdFn(this.sql, githubId);
  }

  async createUserFromGithub(
    githubId: string | number,
    githubLogin: string,
    avatarUrl: string | null,
  ): Promise<DOResult<NewUser & { ok: true }>> {
    this.#ensureSchema();
    return createUserFromGithubFn(this.sql, githubId, githubLogin, avatarUrl);
  }

  async linkGithub(
    userId: string,
    githubId: string | number,
    githubLogin: string,
    avatarUrl: string | null,
  ): Promise<DOResult<{ ok: true }>> {
    this.#ensureSchema();
    return linkGithubFn(this.sql, userId, githubId, githubLogin, avatarUrl);
  }

  async unlinkGithub(userId: string): Promise<{ ok: true }> {
    this.#ensureSchema();
    return unlinkGithubFn(this.sql, userId);
  }

  // -- Web sessions --

  async createWebSession(
    userId: string,
    userAgent: string | null,
  ): Promise<{ ok: true; token: string; expires_at: string }> {
    this.#ensureSchema();
    return createWebSessionFn(this.sql, userId, userAgent);
  }

  async getWebSession(token: string): Promise<DOResult<{ ok: true; session: WebSession }>> {
    this.#ensureSchema();
    return getWebSessionFn(this.sql, token);
  }

  async revokeWebSession(token: string): Promise<{ ok: true }> {
    this.#ensureSchema();
    return revokeWebSessionFn(this.sql, token);
  }

  async getUserWebSessions(userId: string): Promise<{ ok: true; sessions: WebSession[] }> {
    this.#ensureSchema();
    return getUserWebSessionsFn(this.sql, userId);
  }

  // -- Rate limiting --

  async checkRateLimit(key: string, maxPerWindow = 3): Promise<RateLimitCheck & { ok: true }> {
    this.#ensureSchema();
    return checkRateLimitFn(this.sql, key, maxPerWindow);
  }

  async consumeRateLimit(key: string): Promise<{ ok: true }> {
    this.#ensureSchema();
    return consumeRateLimitFn(this.sql, key);
  }

  /**
   * Atomic check-and-consume: checks the limit and increments in one call.
   * Eliminates the race window between separate check and consume calls.
   * Use for public/unauthenticated endpoints where every request should count.
   */
  async checkAndConsume(
    key: string,
    maxPerWindow = 3,
  ): Promise<{ ok: true; allowed: boolean; count: number }> {
    this.#ensureSchema();
    return checkAndConsumeFn(this.sql, key, maxPerWindow);
  }

  // -- Stats --

  async getStats(): Promise<CommunityStats> {
    this.#ensureSchema();
    return getStatsFn(this.sql);
  }

  // -- Global user metrics --

  async updateUserMetrics(
    handle: string,
    summary: Record<string, unknown>,
  ): Promise<{ ok: true } | DOError> {
    this.#ensureSchema();
    return updateUserMetricsFn(this.sql, handle, summary);
  }

  async getUserGlobalRank(
    handle: string,
  ): Promise<{ ok: true; rank: Record<string, unknown> | null; total_developers: number }> {
    this.#ensureSchema();
    return getUserGlobalRankFn(this.sql, handle);
  }

  /**
   * Return the subset of `handles` that already have a user_metrics row.
   * Used by the TeamDO cleanup sweep to figure out which users still need
   * a backfill from historical closed sessions (pre-orphan-fix drift).
   * Cheap batched read: one SQL call regardless of input size.
   */
  async existingMetricsHandles(handles: string[]): Promise<string[]> {
    this.#ensureSchema();
    if (handles.length === 0) return [];
    const placeholders = handles.map(() => '?').join(',');
    const rows = this.sql
      .exec(`SELECT handle FROM user_metrics WHERE handle IN (${placeholders})`, ...handles)
      .toArray() as Array<{ handle: string }>;
    return rows.map((r) => r.handle);
  }

  // -- Tool evaluations (logic in evaluations.ts) --

  async saveEvaluation(evaluation: Record<string, unknown>): Promise<{ ok: true }> {
    this.#ensureSchema();
    // Handlers validate; DO trusts the shape matches EvaluationInput
    return saveEvalFn(this.sql, evaluation as unknown as EvaluationInput);
  }

  async getEvaluation(toolId: string): Promise<ReturnType<typeof getEvalFn>> {
    this.#ensureSchema();
    return getEvalFn(this.sql, toolId);
  }

  async listEvaluations(filters: ListFilters = {}): Promise<ReturnType<typeof listEvalsFn>> {
    this.#ensureSchema();
    return listEvalsFn(this.sql, filters);
  }

  async searchEvaluations(query: string, limit = 20): Promise<ReturnType<typeof searchEvalsFn>> {
    this.#ensureSchema();
    return searchEvalsFn(this.sql, query, limit);
  }

  async deleteEvaluation(toolId: string): Promise<ReturnType<typeof deleteEvalFn>> {
    this.#ensureSchema();
    return deleteEvalFn(this.sql, toolId);
  }

  async getDirectoryStats(): Promise<ReturnType<typeof getDirectoryStatsFn>> {
    this.#ensureSchema();
    return getDirectoryStatsFn(this.sql);
  }

  // -- Model pricing (logic in pricing.ts) --
  //
  // Global pricing snapshot refreshed every 6h by lib/refresh-model-prices.ts.
  // Reads are ordinary SQL queries; writes go through a single transactionSync
  // so analytics reads never see a half-refreshed table. Callers should treat
  // the snapshot as read-mostly and cache it per-isolate in lib/pricing-cache.ts.

  async getModelPricesSnapshot(): Promise<{ ok: true; snapshot: ModelPricesSnapshot }> {
    this.#ensureSchema();
    return { ok: true, snapshot: getModelPricesSnapshotFn(this.sql) };
  }

  async getPricingMetadata(): Promise<{ ok: true; metadata: PricingMetadata | null }> {
    this.#ensureSchema();
    return { ok: true, metadata: getPricingMetadataFn(this.sql) };
  }

  async getModelCanonicalNames(): Promise<{ ok: true; names: string[] }> {
    this.#ensureSchema();
    return { ok: true, names: getModelCanonicalNamesFn(this.sql) };
  }

  async upsertModelPrices(
    rows: ModelPriceInput[],
    metadata: PricingMetadataInput,
  ): Promise<{ ok: true; rows_written: number }> {
    this.#ensureSchema();
    upsertModelPricesTxnFn(this.sql, this.#transact, rows, metadata);
    return { ok: true, rows_written: rows.length };
  }

  async recordPricingRefreshFailure(reason: string): Promise<{ ok: true }> {
    this.#ensureSchema();
    recordRefreshFailureFn(this.sql, this.#transact, reason);
    return { ok: true };
  }

  async seedPricingFromBundled(
    bundled: BundledPricingSeed,
  ): Promise<{ ok: true; seeded: boolean }> {
    this.#ensureSchema();
    const seeded = seedFromBundledFn(this.sql, this.#transact, bundled);
    return { ok: true, seeded };
  }

  // -- User teams --

  async addUserTeam(
    userId: string,
    teamId: string,
    name: string | null = null,
  ): Promise<{ ok: true }> {
    this.#ensureSchema();
    return addUserTeamFn(this.sql, userId, teamId, name);
  }

  async getUserTeams(userId: string): Promise<{ ok: true; teams: UserTeam[] }> {
    this.#ensureSchema();
    return getUserTeamsFn(this.sql, userId);
  }

  async removeUserTeam(userId: string, teamId: string): Promise<{ ok: true }> {
    this.#ensureSchema();
    return removeUserTeamFn(this.sql, userId, teamId);
  }

  // -- Tool suggestions --

  async saveSuggestion(
    suggestion: SuggestionInput,
    userId: string,
    userHandle: string,
  ): Promise<DOResult<{ ok: true; suggestion_id: string }>> {
    this.#ensureSchema();
    return saveSuggestionFn(this.sql, suggestion, userId, userHandle);
  }

  async listSuggestions(
    status = 'pending',
    limit = 50,
  ): Promise<{ ok: true; suggestions: Record<string, unknown>[]; total: number }> {
    this.#ensureSchema();
    return listSuggestionsFn(this.sql, status, limit);
  }

  async reviewSuggestion(
    id: string,
    action: 'approve' | 'reject',
    rejectReason?: string | null,
  ): Promise<DOResult<{ ok: true }>> {
    this.#ensureSchema();
    return reviewSuggestionFn(this.sql, id, action, rejectReason);
  }

  // -- Agent profiles --

  async updateAgentProfile(
    userId: string,
    profile: Partial<AgentProfile>,
  ): Promise<DOResult<{ ok: true }>> {
    this.#ensureSchema();
    return updateAgentProfileFn(this.sql, userId, profile);
  }
}
