// Demo data for visual testing without a backend.
// Activated via ?demo=1 query param.

import type { TeamContext } from './apiSchemas.js';

export function isDemoMode(): boolean {
  if (typeof window === 'undefined') return false;
  return new URLSearchParams(window.location.search).get('demo') === '1';
}

const now = new Date().toISOString();
const ago = (minutes: number) => new Date(Date.now() - minutes * 60_000).toISOString();

export const DEMO_TEAMS = [
  { team_id: 'demo-team-1', team_name: 'chinwag', joined_at: ago(60 * 24 * 30) },
];

export const DEMO_USER = {
  id: 'demo-user',
  handle: 'glendon',
  color: 'cyan',
  status: null,
  github_login: 'glendonchin',
  avatar_url: null,
  created_at: ago(60 * 24 * 90),
  last_active: now,
};

export function createDemoContext(): TeamContext {
  return {
    members: [
      {
        agent_id: 'claude-code:demo-1',
        handle: 'glendon',
        host_tool: 'claude-code',
        agent_surface: 'cli',
        transport: 'stdio',
        agent_model: 'claude-sonnet-4-5-20250514',
        status: 'active',
        session_minutes: 47,
        activity: {
          files: [
            'packages/worker/src/dos/team/categories.ts',
            'packages/web/src/views/ProjectView/ProjectMemoryTab.tsx',
          ],
          summary: 'Building memory categories system',
          updated_at: ago(1),
        },
        color: 'cyan',
      },
      {
        agent_id: 'cursor:demo-2',
        handle: 'glendon',
        host_tool: 'cursor',
        agent_surface: 'ide',
        transport: 'sse',
        agent_model: 'claude-sonnet-4-5-20250514',
        status: 'offline',
        session_minutes: null,
        activity: null,
        color: 'lavender',
      },
    ] as TeamContext['members'],
    memory_categories: [
      {
        id: 'cat-1',
        name: 'architecture',
        description: 'System design decisions, patterns, and structural choices',
        color: '#6366f1',
        created_at: ago(60 * 24 * 7),
      },
      {
        id: 'cat-2',
        name: 'security',
        description: 'Authentication, authorization, vulnerability fixes',
        color: '#ef4444',
        created_at: ago(60 * 24 * 7),
      },
      {
        id: 'cat-3',
        name: 'setup',
        description: 'Environment setup, configuration, tooling',
        color: '#22c55e',
        created_at: ago(60 * 24 * 5),
      },
      {
        id: 'cat-4',
        name: 'conventions',
        description: 'Code style, naming patterns, file organization',
        color: '#f59e0b',
        created_at: ago(60 * 24 * 5),
      },
      {
        id: 'cat-5',
        name: 'gotchas',
        description: 'Non-obvious behaviors, footguns, things that tripped us up',
        color: '#ec4899',
        created_at: ago(60 * 24 * 3),
      },
    ],
    memories: [
      {
        id: 'mem-1',
        text: 'SQLite on Durable Objects has no native vector operations. Use brute-force cosine similarity in JS for small corpora (<5k entries). Store embeddings as BLOBs.',
        tags: ['sqlite', 'embeddings'],
        categories: ['architecture', 'gotchas'],
        handle: 'glendon',
        host_tool: 'claude-code',
        agent_surface: 'cli',
        agent_model: 'claude-sonnet-4-5-20250514',
        created_at: ago(120),
        updated_at: ago(120),
        last_accessed_at: ago(30),
      },
      {
        id: 'mem-2',
        text: 'All AI moderation uses Llama Guard 3 via env.AI binding. No external API keys needed. Blocklist runs first (sync), AI runs second (async).',
        tags: ['moderation', 'cloudflare'],
        categories: ['architecture'],
        handle: 'glendon',
        host_tool: 'claude-code',
        agent_surface: 'cli',
        agent_model: 'claude-sonnet-4-5-20250514',
        created_at: ago(180),
        updated_at: ago(180),
        last_accessed_at: ago(60),
      },
      {
        id: 'mem-3',
        text: 'Every read endpoint must verify the caller has access. Never assume the URL is proof of authorization. Unauthenticated reads are bugs.',
        tags: ['auth'],
        categories: ['security'],
        handle: 'glendon',
        host_tool: 'cursor',
        agent_surface: 'ide',
        agent_model: 'claude-sonnet-4-5-20250514',
        created_at: ago(60 * 24),
        updated_at: ago(60 * 24),
        last_accessed_at: ago(60 * 3),
      },
      {
        id: 'mem-4',
        text: 'Access tokens use 90-day sliding window TTL. Every auth re-PUTs the KV entry. Web sessions get 30 days. Refresh tokens last 180 days.',
        tags: ['tokens', 'auth'],
        categories: ['security', 'conventions'],
        handle: 'glendon',
        host_tool: 'claude-code',
        agent_surface: 'cli',
        agent_model: 'claude-sonnet-4-5-20250514',
        created_at: ago(60 * 48),
        updated_at: ago(60 * 48),
        last_accessed_at: ago(60 * 12),
      },
      {
        id: 'mem-5',
        text: 'Run npx wrangler dev in packages/worker for local dev. The CLI is cd packages/cli && npm run dev. Web is npm run dev in packages/web.',
        tags: ['dev-server'],
        categories: ['setup'],
        handle: 'glendon',
        host_tool: 'claude-code',
        agent_surface: 'cli',
        agent_model: 'claude-sonnet-4-5-20250514',
        created_at: ago(60 * 72),
        updated_at: ago(60 * 72),
        last_accessed_at: ago(60 * 2),
      },
      {
        id: 'mem-6',
        text: 'MCP server must never use console.log \u2014 stdio transport uses stdout for JSON-RPC. Use console.error for all logging.',
        tags: ['mcp'],
        categories: ['gotchas', 'conventions'],
        handle: 'glendon',
        host_tool: 'cursor',
        agent_surface: 'ide',
        agent_model: 'gpt-4o',
        created_at: ago(60 * 96),
        updated_at: ago(60 * 96),
        last_accessed_at: ago(60 * 24),
      },
      {
        id: 'mem-7',
        text: 'DO methods return {ok:true} or {error:string}. Route handlers check .error and return HTTP status. Throws are for unexpected failures only.',
        tags: ['patterns'],
        categories: ['conventions'],
        handle: 'glendon',
        host_tool: 'claude-code',
        agent_surface: 'cli',
        agent_model: 'claude-sonnet-4-5-20250514',
        created_at: ago(60 * 120),
        updated_at: ago(60 * 120),
        last_accessed_at: null,
      },
      {
        id: 'mem-8',
        text: 'Memory cap raised to 2000. Pruning is decay-aware: last_accessed_at DESC, then updated_at DESC, then created_at DESC. Unused memories evict first.',
        tags: ['memory', 'lifecycle'],
        categories: ['architecture'],
        handle: 'glendon',
        host_tool: 'claude-code',
        agent_surface: 'cli',
        agent_model: 'claude-sonnet-4-5-20250514',
        created_at: ago(15),
        updated_at: ago(15),
        last_accessed_at: ago(5),
      },
      {
        id: 'mem-9',
        text: 'Node 22+ required for CLI \u2014 native WebSocket support. Built with esbuild to dist/cli.js. Entry point is cli.jsx.',
        tags: ['cli', 'node'],
        categories: ['setup'],
        handle: 'glendon',
        host_tool: 'claude-code',
        agent_surface: 'cli',
        agent_model: 'claude-sonnet-4-5-20250514',
        created_at: ago(60 * 168),
        updated_at: ago(60 * 168),
        last_accessed_at: ago(60 * 48),
      },
      {
        id: 'mem-10',
        text: 'Rate limits: 20 memory saves/day, 50 updates/day, 50 deletes/day per user. Categories: 50/day. Enforced at route layer via withTeamRateLimit.',
        tags: ['rate-limits'],
        categories: ['security', 'conventions'],
        handle: 'glendon',
        host_tool: 'claude-code',
        agent_surface: 'cli',
        agent_model: 'claude-sonnet-4-5-20250514',
        created_at: ago(60 * 36),
        updated_at: ago(60 * 36),
        last_accessed_at: null,
      },
      {
        id: 'mem-11',
        text: '12-color palette for user identity: red, cyan, yellow, green, magenta, blue, orange, lime, pink, sky, lavender, white.',
        tags: ['design', 'colors'],
        categories: [],
        handle: 'glendon',
        host_tool: 'cursor',
        agent_surface: 'ide',
        agent_model: 'claude-sonnet-4-5-20250514',
        created_at: ago(60 * 200),
        updated_at: ago(60 * 200),
        last_accessed_at: null,
      },
      {
        id: 'mem-12',
        text: 'Handle format: 3-20 chars, alphanumeric + underscores, globally unique across all teams.',
        tags: ['validation'],
        categories: [],
        handle: 'glendon',
        host_tool: 'claude-code',
        agent_surface: 'cli',
        agent_model: 'claude-sonnet-4-5-20250514',
        created_at: ago(60 * 240),
        updated_at: ago(60 * 240),
        last_accessed_at: null,
      },
    ],
    locks: [],
    messages: [],
    recentSessions: [
      {
        owner_handle: 'glendon',
        framework: 'unknown',
        host_tool: 'claude-code',
        agent_surface: 'cli',
        transport: 'stdio',
        agent_model: 'claude-sonnet-4-5-20250514',
        started_at: ago(47),
        ended_at: null,
        edit_count: 34,
        files_touched: [
          'packages/worker/src/dos/team/categories.ts',
          'packages/worker/src/dos/team/memory.ts',
          'packages/web/src/views/ProjectView/ProjectMemoryTab.tsx',
        ],
        conflicts_hit: 0,
        memories_saved: 3,
        outcome: null,
        outcome_summary: null,
        lines_added: 412,
        lines_removed: 87,
        duration_minutes: 47,
        tool: 'claude-code',
      },
    ] as TeamContext['recentSessions'],
    sessions: [],
    conflicts: [],
    tools_configured: [
      { host_tool: 'claude-code', joins: 14 },
      { host_tool: 'cursor', joins: 6 },
    ],
    hosts_configured: [
      { host_tool: 'claude-code', joins: 14 },
      { host_tool: 'cursor', joins: 6 },
    ],
    surfaces_seen: [
      { agent_surface: 'cli', joins: 14 },
      { agent_surface: 'ide', joins: 6 },
    ],
    models_seen: [
      { agent_model: 'claude-sonnet-4-5-20250514', count: 18 },
      { agent_model: 'gpt-4o', count: 2 },
    ],
    usage: {
      joins: 20,
      memories_saved: 42,
      conflict_checks: 156,
      conflicts_found: 3,
    },
    daemon: { connected: false, available_tools: [] },
  };
}
