// Comprehensive tool seed list for the directory.
// Compiled from multi-source agent research across 13 categories.
// Deduplicated, organized by category.
//
// Usage: npx tsx scripts/import-seed-tools.ts
// Tools are imported via admin-import endpoint, enriched via agent research scripts.

export interface SeedTool {
  name: string;
  category: string;
}

export const SEED_TOOLS: SeedTool[] = [
  // ── Editors ──
  { name: 'Cursor', category: 'editors' },
  { name: 'Windsurf', category: 'editors' },
  { name: 'Zed', category: 'editors' },
  { name: 'Trae', category: 'editors' },
  { name: 'Kiro', category: 'editors' },
  { name: 'PearAI', category: 'editors' },
  { name: 'Aide by CodeStory', category: 'editors' },
  { name: 'Void Editor', category: 'editors' },
  { name: 'Google Antigravity IDE', category: 'editors' },
  { name: 'Neovim', category: 'editors' },

  // ── Coding Agents ──
  { name: 'Claude Code', category: 'coding-agents' },
  { name: 'OpenAI Codex CLI', category: 'coding-agents' },
  { name: 'Aider', category: 'coding-agents' },
  { name: 'Gemini CLI', category: 'coding-agents' },
  { name: 'GitHub Copilot CLI', category: 'coding-agents' },
  { name: 'OpenCode', category: 'coding-agents' },
  { name: 'Goose by Block', category: 'coding-agents' },
  { name: 'Qwen Code', category: 'coding-agents' },
  { name: 'Amp by Sourcegraph', category: 'coding-agents' },
  { name: 'Warp', category: 'coding-agents' },
  { name: 'GitHub Copilot', category: 'coding-agents' },
  { name: 'Tabnine', category: 'coding-agents' },
  { name: 'Codeium', category: 'coding-agents' },
  { name: 'Blackbox AI', category: 'coding-agents' },
  { name: 'Gemini Code Assist', category: 'coding-agents' },
  { name: 'Cline', category: 'coding-agents' },
  { name: 'Continue', category: 'coding-agents' },
  { name: 'Roo Code', category: 'coding-agents' },
  { name: 'Kilo Code', category: 'coding-agents' },
  { name: 'Amazon Q Developer', category: 'coding-agents' },
  { name: 'Augment Code', category: 'coding-agents' },
  { name: 'Sourcegraph Cody', category: 'coding-agents' },
  { name: 'Refact.ai', category: 'coding-agents' },
  { name: 'Qodo', category: 'coding-agents' },
  { name: 'Devin', category: 'coding-agents' },
  { name: 'GitHub Copilot Coding Agent', category: 'coding-agents' },
  { name: 'Replit Agent', category: 'coding-agents' },
  { name: 'v0 by Vercel', category: 'coding-agents' },
  { name: 'Bolt.new', category: 'coding-agents' },
  { name: 'Lovable', category: 'coding-agents' },
  { name: 'Google Stitch', category: 'coding-agents' },

  // ── Code Quality ──
  { name: 'CodeRabbit', category: 'code-quality' },
  { name: 'Graphite', category: 'code-quality' },
  { name: 'Ellipsis', category: 'code-quality' },
  { name: 'Greptile', category: 'code-quality' },
  { name: 'Sourcery', category: 'code-quality' },
  { name: 'Bito', category: 'code-quality' },
  { name: 'Korbit AI', category: 'code-quality' },
  { name: 'CodeScene', category: 'code-quality' },
  { name: 'Codacy', category: 'code-quality' },
  { name: 'ESLint', category: 'code-quality' },
  { name: 'Biome', category: 'code-quality' },
  { name: 'Oxlint', category: 'code-quality' },
  { name: 'SonarQube', category: 'code-quality' },
  { name: 'DeepSource', category: 'code-quality' },
  { name: 'Trunk', category: 'code-quality' },
  { name: 'Prettier', category: 'code-quality' },

  // ── Testing ──
  { name: 'Playwright', category: 'testing' },
  { name: 'Cypress', category: 'testing' },
  { name: 'Applitools', category: 'testing' },
  { name: 'Percy by BrowserStack', category: 'testing' },
  { name: 'Chromatic', category: 'testing' },
  { name: 'Meticulous', category: 'testing' },
  { name: 'Stryker Mutator', category: 'testing' },
  { name: 'Codecov', category: 'testing' },
  { name: 'Vitest', category: 'testing' },
  { name: 'Jest', category: 'testing' },
  { name: 'pytest', category: 'testing' },
  { name: 'Selenium', category: 'testing' },

  // ── Security ──
  { name: 'Snyk', category: 'security' },
  { name: 'Semgrep', category: 'security' },
  { name: 'Socket', category: 'security' },
  { name: 'GitGuardian', category: 'security' },
  { name: 'Trivy', category: 'security' },
  { name: 'GitHub CodeQL', category: 'security' },
  { name: 'Aikido Security', category: 'security' },
  { name: 'OWASP ZAP', category: 'security' },
  { name: 'Burp Suite', category: 'security' },
  { name: 'Wiz', category: 'security' },

  // ── Data & Search ──
  { name: 'Exa', category: 'data-search' },
  { name: 'Tavily', category: 'data-search' },
  { name: 'Perplexity API', category: 'data-search' },
  { name: 'Brave Search API', category: 'data-search' },
  { name: 'Jina AI', category: 'data-search' },
  { name: 'SerpAPI', category: 'data-search' },
  { name: 'Serper', category: 'data-search' },
  { name: 'You.com API', category: 'data-search' },
  { name: 'Firecrawl', category: 'data-search' },
  { name: 'Crawl4AI', category: 'data-search' },
  { name: 'Browserbase', category: 'data-search' },
  { name: 'Stagehand', category: 'data-search' },
  { name: 'Browser Use', category: 'data-search' },
  { name: 'Apify', category: 'data-search' },
  { name: 'Puppeteer', category: 'data-search' },
  { name: 'LlamaParse', category: 'data-search' },
  { name: 'Unstructured', category: 'data-search' },
  { name: 'Postman', category: 'data-search' },

  // ── AI Models ──
  { name: 'OpenAI API', category: 'ai-models' },
  { name: 'Anthropic API', category: 'ai-models' },
  { name: 'Google Gemini API', category: 'ai-models' },
  { name: 'Groq', category: 'ai-models' },
  { name: 'Together AI', category: 'ai-models' },
  { name: 'Fireworks AI', category: 'ai-models' },
  { name: 'Cerebras', category: 'ai-models' },
  { name: 'Replicate', category: 'ai-models' },
  { name: 'OpenRouter', category: 'ai-models' },
  { name: 'LiteLLM', category: 'ai-models' },
  { name: 'Portkey', category: 'ai-models' },
  { name: 'Cloudflare Workers AI', category: 'ai-models' },
  { name: 'Amazon Bedrock', category: 'ai-models' },
  { name: 'Hugging Face', category: 'ai-models' },
  { name: 'Mistral API', category: 'ai-models' },
  { name: 'Ollama', category: 'ai-models' },

  // ── Databases ──
  { name: 'Supabase', category: 'databases' },
  { name: 'Neon', category: 'databases' },
  { name: 'Pinecone', category: 'databases' },
  { name: 'Weaviate', category: 'databases' },
  { name: 'Qdrant', category: 'databases' },
  { name: 'Chroma', category: 'databases' },
  { name: 'Turbopuffer', category: 'databases' },
  { name: 'Upstash', category: 'databases' },
  { name: 'Prisma', category: 'databases' },
  { name: 'Drizzle ORM', category: 'databases' },
  { name: 'PostgreSQL', category: 'databases' },
  { name: 'Redis', category: 'databases' },
  { name: 'MongoDB', category: 'databases' },

  // ── Infrastructure ──
  { name: 'Bun', category: 'infrastructure' },
  { name: 'Deno', category: 'infrastructure' },
  { name: 'Node.js', category: 'infrastructure' },
  { name: 'Vite', category: 'infrastructure' },
  { name: 'esbuild', category: 'infrastructure' },
  { name: 'Rspack', category: 'infrastructure' },
  { name: 'Turbopack', category: 'infrastructure' },
  { name: 'Turborepo', category: 'infrastructure' },
  { name: 'Nx', category: 'infrastructure' },
  { name: 'pnpm', category: 'infrastructure' },
  { name: 'mise', category: 'infrastructure' },
  { name: 'Vercel', category: 'infrastructure' },
  { name: 'Netlify', category: 'infrastructure' },
  { name: 'Cloudflare Pages', category: 'infrastructure' },
  { name: 'Railway', category: 'infrastructure' },
  { name: 'Fly.io', category: 'infrastructure' },
  { name: 'Render', category: 'infrastructure' },
  { name: 'Docker', category: 'infrastructure' },
  { name: 'Coolify', category: 'infrastructure' },
  { name: 'GitHub Actions', category: 'infrastructure' },
  { name: 'GitLab CI', category: 'infrastructure' },
  { name: 'CircleCI', category: 'infrastructure' },
  { name: 'Dagger', category: 'infrastructure' },
  { name: 'Depot', category: 'infrastructure' },
  { name: 'E2B', category: 'infrastructure' },
  { name: 'Daytona', category: 'infrastructure' },
  { name: 'Trigger.dev', category: 'infrastructure' },
  { name: 'Inngest', category: 'infrastructure' },
  { name: 'Val Town', category: 'infrastructure' },
  { name: 'Terraform', category: 'infrastructure' },
  { name: 'Webpack', category: 'infrastructure' },
  { name: 'Kubernetes', category: 'infrastructure' },

  // ── Terminal & CLI ──
  { name: 'Ghostty', category: 'terminal-cli' },
  { name: 'WezTerm', category: 'terminal-cli' },
  { name: 'Alacritty', category: 'terminal-cli' },
  { name: 'Kitty', category: 'terminal-cli' },
  { name: 'Zellij', category: 'terminal-cli' },
  { name: 'tmux', category: 'terminal-cli' },
  { name: 'fzf', category: 'terminal-cli' },
  { name: 'ripgrep', category: 'terminal-cli' },
  { name: 'bat', category: 'terminal-cli' },
  { name: 'eza', category: 'terminal-cli' },
  { name: 'delta', category: 'terminal-cli' },
  { name: 'starship', category: 'terminal-cli' },
  { name: 'zoxide', category: 'terminal-cli' },
  { name: 'fd', category: 'terminal-cli' },
  { name: 'jq', category: 'terminal-cli' },
  { name: 'yazi', category: 'terminal-cli' },
  { name: 'Nushell', category: 'terminal-cli' },
  { name: 'fish shell', category: 'terminal-cli' },
  { name: 'Lazygit', category: 'terminal-cli' },
  { name: 'btop', category: 'terminal-cli' },
  { name: 'iTerm2', category: 'terminal-cli' },
  { name: 'Oh My Zsh', category: 'terminal-cli' },

  // ── Collaboration ──
  { name: 'GitHub CLI', category: 'collaboration' },
  { name: 'GitButler', category: 'collaboration' },
  { name: 'GitKraken', category: 'collaboration' },
  { name: 'Fork Git Client', category: 'collaboration' },
  { name: 'WisprFlow', category: 'collaboration' },
  { name: 'Superwhisper', category: 'collaboration' },
  { name: 'Talon Voice', category: 'collaboration' },
  { name: 'Obsidian', category: 'collaboration' },
  { name: 'Notion', category: 'collaboration' },
  { name: 'Raycast', category: 'collaboration' },
  { name: 'Pieces for Developers', category: 'collaboration' },
  { name: 'Slack', category: 'collaboration' },
  { name: 'Linear', category: 'collaboration' },
  { name: 'Jira', category: 'collaboration' },
  { name: 'Discord', category: 'collaboration' },
  { name: 'Loom', category: 'collaboration' },
  { name: 'Tuple', category: 'collaboration' },

  // ── Documentation ──
  { name: 'Mintlify', category: 'documentation' },
  { name: 'GitBook', category: 'documentation' },
  { name: 'ReadMe', category: 'documentation' },
  { name: 'Docusaurus', category: 'documentation' },
  { name: 'Redocly', category: 'documentation' },
  { name: 'Excalidraw', category: 'documentation' },
  { name: 'tldraw', category: 'documentation' },
  { name: 'Mermaid', category: 'documentation' },
  { name: 'Eraser', category: 'documentation' },
  { name: 'D2 by Terrastruct', category: 'documentation' },
  { name: 'Draw.io', category: 'documentation' },
  { name: 'Speakeasy', category: 'documentation' },
  { name: 'Stainless', category: 'documentation' },
  { name: 'Fern', category: 'documentation' },

  // ── AI Frameworks ──
  { name: 'LangChain', category: 'ai-frameworks' },
  { name: 'LangGraph', category: 'ai-frameworks' },
  { name: 'CrewAI', category: 'ai-frameworks' },
  { name: 'Mastra', category: 'ai-frameworks' },
  { name: 'OpenAI Agents SDK', category: 'ai-frameworks' },
  { name: 'Claude Agent SDK', category: 'ai-frameworks' },
  { name: 'Google ADK', category: 'ai-frameworks' },
  { name: 'Vercel AI SDK', category: 'ai-frameworks' },
  { name: 'LlamaIndex', category: 'ai-frameworks' },
  { name: 'Pydantic AI', category: 'ai-frameworks' },
  { name: 'DSPy', category: 'ai-frameworks' },
  { name: 'Dify', category: 'ai-frameworks' },
  { name: 'n8n', category: 'ai-frameworks' },
  { name: 'Langfuse', category: 'ai-frameworks' },
  { name: 'LangSmith', category: 'ai-frameworks' },
  { name: 'Helicone', category: 'ai-frameworks' },
  { name: 'Braintrust', category: 'ai-frameworks' },
  { name: 'Arize Phoenix', category: 'ai-frameworks' },
  { name: 'Mem0', category: 'ai-frameworks' },
  { name: 'Zep', category: 'ai-frameworks' },
  { name: 'Letta', category: 'ai-frameworks' },
  { name: 'Composio', category: 'ai-frameworks' },
  { name: 'Smithery', category: 'ai-frameworks' },
];

// Quick stats
export const SEED_STATS = {
  total: SEED_TOOLS.length,
  categories: [...new Set(SEED_TOOLS.map((t) => t.category))].length,
  categoryBreakdown: SEED_TOOLS.reduce(
    (acc, t) => {
      acc[t.category] = (acc[t.category] || 0) + 1;
      return acc;
    },
    {} as Record<string, number>,
  ),
};
