// Re-export from split sub-routers for backwards compatibility.
// New code should import from './team/index.js' directly.
export {
  handleTeamJoin,
  handleTeamLeave,
  handleTeamContext,
  handleTeamHeartbeat,
  handleTeamWebSocket,
  handleTeamActivity,
  handleTeamConflicts,
  handleTeamFile,
  handleTeamStartSession,
  handleTeamEndSession,
  handleTeamSessionEdit,
  handleTeamHistory,
  handleTeamEnrichModel,
  handleTeamSaveMemory,
  handleTeamSearchMemory,
  handleTeamUpdateMemory,
  handleTeamDeleteMemory,
  handleTeamClaimFiles,
  handleTeamReleaseFiles,
  handleTeamGetLocks,
  handleTeamSendMessage,
  handleTeamGetMessages,
} from './team/index.js';
